### ISSUE TITLE
no method error?

### ISSUE THREAD

**Issue by chenge** [CrowdHailer/vulcanize#4]
form.email

Where is the email?

**Comment by CrowdHailer** [comment]
Is this in the readme somewhere?
an example of an email implementation this form would work with can be found in the [typetanic repo](https://github.com/CrowdHailer/typetanic)
Is that what you are after? probably need a bit more information

**Comment by CrowdHailer** [comment]
found what you mean changing it now

**Comment by chenge** [comment]
![2015-08-24 10 26 47](https://cloud.githubusercontent.com/assets/252333/9431779/9a4b8cc6-4a4a-11e5-9593-11a0beb3aeb7.png)

**Comment by CrowdHailer** [comment]
> If we have a Name domain object we can use it in a vulcanize form as follows. Notes below on creating domain object.

Vulcanize relies on you providing the custom value types, of which name is an example. Perhaps that comment in the readme I've copied is not enough and I should put the information about defining a custom type nearer the top
